CREATE DATABASE [saasdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'saasdb', FILENAME = N'/var/opt/mssql/data/saasdb.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'saasdb_log', FILENAME = N'/var/opt/mssql/data/saasdb_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 COLLATE SQL_Latin1_General_CP1_CI_AS
 WITH LEDGER = OFF
GO
ALTER DATABASE [saasdb] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [saasdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [saasdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [saasdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [saasdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [saasdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [saasdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [saasdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [saasdb] SET AUTO_CREATE_STATISTICS OFF
GO
ALTER DATABASE [saasdb] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [saasdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [saasdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [saasdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [saasdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [saasdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [saasdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [saasdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [saasdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [saasdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [saasdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [saasdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [saasdb] SET  READ_WRITE 
GO
ALTER DATABASE [saasdb] SET RECOVERY FULL 
GO
ALTER DATABASE [saasdb] SET  MULTI_USER 
GO
ALTER DATABASE [saasdb] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO
ALTER DATABASE [saasdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [saasdb] SET DELAYED_DURABILITY = DISABLED 
GO
USE [saasdb]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [saasdb] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
