name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ef-commands:
    runs-on: ubuntu-latest
    steps:
     # Check out the repository
      - uses: actions/checkout@v4
      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify the required .NET version
      # Install dependencies
      - name: Install dependencies
        run: dotnet restore
      - name: Run EF Commands
        run: |
          dotnet ef migrations add InitialCreate --project GTM.Cloud.SaaS.Database --startup-project GTM.Cloud.SaaS.Web
          dotnet ef database update --project GTM.Cloud.SaaS.Database --startup-project GTM.Cloud.SaaS.Web

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup EF Tools
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fthornton67/gtm-cloud-saas-db:latest

      - name: Log in to container registry
        run: docker login -u fthornton67 -p ${{ secrets.docker_access_token }}

      - name: Push the Docker image
        run: docker push fthornton67/gtm-cloud-saas-db:latest
