name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ef-commands:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      sql: sql/install.sql
    steps:
     # Check out the repository
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify the required .NET version
      # Install dependencies
      - name: Install dependencies
        run: dotnet restore
      - name: Run EF Commands
        run: |
          dotnet tool install --global dotnet-ef
      - name: Update Database
        run: |
            dotnet ef migrations script -o sql/install.sql
      - name: Setup GitHub CLI
        run: |
          type -p gh || (apt update && apt install gh)
      - name: Commit SQL Script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -f sql/install.sql ]]; then
            gh auth setup-git
            git add sql/install.sql
            git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update database migration script [skip ci]" && git push)
          else
            echo "No sql/install.sql file found"
          fi
      - name: Upload SQL Script
        uses: actions/upload-artifact@v4
        with:
          name: sql-script
          path: sql/install.sql

  build:
    needs: ef-commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup EF Tools
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag fthornton67/gtm-cloud-saas-db:latest

      - name: Log in to container registry
        run: docker login -u fthornton67 -p ${{ secrets.docker_access_token }}

      - name: Push the Docker image
        run: docker push fthornton67/gtm-cloud-saas-db:latest
