name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log in to container registry
      run:  docker login containers.HOSTNAME -u USERNAME -p ${{ secrets.CLASSIC_TOKEN }}
    - name: Push the Docker image
      run: docker push containers.HOSTNAME/my-image-name:$(date +%s)
  